[project]
name = "news-bot"
version = "0.1.0"
description = "An AI-powered news summarizer and notifier for Telegram"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.4",
    "httpx>=0.27.2",
]
